#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -ea -cp 'jars/*':"bin" -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     launcher.DistributedCVM $1 config.xml