#!/bin/bash
java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher/DCVM controleur config.xml

java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DCVM eolienne config.xml
java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DistributedCVM batterie config.xml

java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DistributedCVM compteur config.xml
java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DistributedCVM bouilloire config.xml
java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DistributedCVM chauffage config.xml
java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DistributedCVM chargeur config.xml

java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DistributedCVM capteurChaleur config.xml
java -ea -cp 'jars/*':'bin' -Djava.security.manager -Djava.security.policy=dcvm.policy launcher.DistributedCVM capteurVent config.xml